#!/usr/bin/env python3

import argparse
from os import PathLike
import os
import json
from dataclasses import dataclass
from tempfile import TemporaryDirectory
from contextlib import contextmanager
from typing import Generator
import subprocess


class Args:
    image: str
    repart_out: str


def parseArgs() -> Args:
    parser = argparse.ArgumentParser()
    parser.add_argument("image")
    parser.add_argument("repart_out")
    args = parser.parse_args(namespace=Args())

    return args


@dataclass
class RepartOutEntry:
    type: str
    label: str
    uuid: str
    partno: int
    file: str
    node: str
    offset: int
    old_size: int
    raw_size: int
    old_padding: int
    raw_padding: int
    activity: str


def load_repart_out(path: str | PathLike[str]) -> list[RepartOutEntry]:
    raw = None
    with open(path) as fp:
        raw = json.load(fp)

    if not isinstance(raw, list):
        raise Exception("unexpected type")

    result: list[RepartOutEntry] = []
    for entry in raw:
        if not isinstance(entry, dict):
            raise Exception("unexpected type")
        result.append(RepartOutEntry(**entry))

    return result


def esp_offset(entries: list[RepartOutEntry]) -> tuple[int, int]:
    for entry in entries:
        if entry.type != "esp":
            continue

        return (entry.offset, entry.raw_size)

    raise Exception("no esp found.")


def root_partuuid(entries: list[RepartOutEntry]) -> str:
    for entry in entries:
        if not entry.type.startswith("root"):
            continue

        return entry.uuid

    raise Exception("no root found.")


@contextmanager
def loop_mount(image: str | PathLike[str], off: int, size: int) -> Generator[str]:
    with TemporaryDirectory() as tmpdir:
        # TODO failed to set up loop device for
        subprocess.run(["mount", "-o", f"loop,offset={off},sizelimit={size}", os.fspath(image), tmpdir], check=True)
        try:
            yield tmpdir
        finally:
            subprocess.run(["umount", tmpdir], check=False)


def main():
    args = parseArgs()

    entries = load_repart_out(args.repart_out)
    (off, size) = esp_offset(entries)
    partuuid = root_partuuid(entries)

    with loop_mount(args.image, off, size) as mnt:
        pass
    print(off, partuuid)


if __name__ == "__main__":
    main()
