#!/usr/bin/env python3

import argparse
from os import PathLike
import os
import json
from dataclasses import dataclass
from tempfile import NamedTemporaryFile
from contextlib import contextmanager
from typing import Generator, Protocol, TypeVar
import subprocess


class Args:
    image: str
    repart_out: str


def parseArgs() -> Args:
    parser = argparse.ArgumentParser()
    parser.add_argument("image")
    parser.add_argument("repart_out")
    args = parser.parse_args(namespace=Args())

    return args


@dataclass
class RepartOutEntry:
    type: str
    label: str
    uuid: str
    partno: int
    file: str
    node: str
    offset: int
    old_size: int
    raw_size: int
    old_padding: int
    raw_padding: int
    activity: str


def load_repart_out(path: str | PathLike[str]) -> list[RepartOutEntry]:
    raw = None
    with open(path) as fp:
        raw = json.load(fp)

    if not isinstance(raw, list):
        raise Exception("unexpected type")

    result: list[RepartOutEntry] = []
    for entry in raw:
        if not isinstance(entry, dict):
            raise Exception("unexpected type")
        result.append(RepartOutEntry(**entry))

    return result


def esp_offset(entries: list[RepartOutEntry]) -> tuple[int, int]:
    for entry in entries:
        if entry.type != "esp":
            continue

        return (entry.offset, entry.raw_size)

    raise Exception("no esp found.")


def root_partuuid(entries: list[RepartOutEntry]) -> str:
    for entry in entries:
        if not entry.type.startswith("root"):
            continue

        return entry.uuid

    raise Exception("no root found.")


T = TypeVar("T", contravariant=True)

class SupportsWrite(Protocol[T]):
    def write(self, data: T, /) -> int: ...


def write_grub_cfg(dest: SupportsWrite, partuuid: str):
    print("set timeout=1", file=dest)
    print("set default=0", file=dest)
    print("", file=dest)
    print('menuentry "Linux From Scratch" {', file=dest)
    print(f"    linux /vmlinuz-7.1.8-lfs-13.1-systemd root=PARTUUID={partuuid} ro console=ttyS0,115200 console=tty0 console=hvc0", file=dest)
    print("}", file=dest)


def main():
    args = parseArgs()

    entries = load_repart_out(args.repart_out)
    (off, size) = esp_offset(entries)
    partuuid = root_partuuid(entries)

    with NamedTemporaryFile(mode="w") as tmp:
        write_grub_cfg(tmp, partuuid)
        tmp.flush()

        subprocess.check_call([
            "mcopy",
            "-o",
            "-i",
            f"{args.image}@@{off}",
            tmp.name,
            "::/grub/grub.cfg",
        ])


if __name__ == "__main__":
    main()
