stamps := .stamps

c1 := 1.Introduction
c2 := 2.Package_Management
c3 := 3.Man-pages-6.18
c4 := 4.Iana-Etc-20260805
c5 := 5.Glibc-2.44
c6 := 6.Zlib-1.3.2
c7 := 7.Bzip2-1.0.8
c8 := 8.Xz-5.8.3
c9 := 9.Lz4-1.10.0
c10 := 10.Zstd-1.5.7
c11 := 11.File-5.48
c12 := 12.Readline-8.3
c13 := 13.Pcre2-10.47
c14 := 14.M4-1.4.21
c15 := 15.Bc-7.0.3
c16 := 16.Flex-2.6.4
c17 := 17.Tcl-8.6.18
c18 := 18.Expect-5.45.4
c19 := 19.DejaGNU-1.6.3
c20 := 20.Ninja-1.13.2
c21 := 21.Pkgconf-3.0.5
c22 := 22.Binutils-2.47
c23 := 23.GMP-6.3.0
c24 := 24.MPFR-4.2.2
c25 := 25.MPC-1.4.1
c26 := 26.Attr-2.6.0
c27 := 27.Acl-2.4.0
c28 := 28.Libcap-2.78
c29 := 29.Libxcrypt-4.5.2
c30 := 30.Shadow-4.20.2
c31 := 31.Gawk-5.4.1
c32 := 32.GCC-16.2.0
c33 := 33.Ncurses-6.6
c34 := 34.Sed-4.10
c35 := 35.Psmisc-23.7
c36 := 36.Gettext-1.0
c37 := 37.Bison-3.8.2
c38 := 38.Grep-3.12
c39 := 39.Bash-5.3
c40 := 40.Libtool-2.6.2
c41 := 41.GDBM-1.26
c42 := 42.Gperf-3.3
c43 := 43.Expat-2.8.3
c44 := 44.Inetutils-2.8
c45 := 45.Less-704
c46 := 46.Perl-5.44.0
c47 := 47.Autoconf-2.73
c48 := 48.Automake-1.18.1
c49 := 49.OpenSSL-4.0.1
c50 := 50.Libelf_from_Elfutils-0.195
c51 := 51.Libffi-3.8.0
c52 := 52.Sqlite-3530400
c53 := 53.mpdecimal-4.0.1
c54 := 54.Python-3.14.7
c55 := 55.Flit-Core-4.0.2
c56 := 56.Packaging-26.3
c57 := 57.Wheel-0.48.0
c58 := 58.Setuptools-84.0.0
c59 := 59.Meson-1.12.0
c60 := 60.Kmod-34.2
c61 := 61.Coreutils-9.11
c62 := 62.Diffutils-3.12
c63 := 63.Findutils-4.11.0
c64 := 64.Groff-1.24.1
c65 := 65.GRUB-2.14
c66 := 66.Gzip-1.14
c67 := 67.IPRoute2-7.1.0
c68 := 68.Kbd-2.10.0
c69 := 69.Libpipeline-1.5.8
c70 := 70.Make-4.4.1
c71 := 71.Patch-2.8
c72 := 72.Tar-1.35
c73 := 73.Texinfo-7.3
c74 := 74.Vim-9.2.1025
c75 := 75.MarkupSafe-3.0.3
c76 := 76.Jinja2-3.1.6
c77 := 77.Systemd-261.2
c78 := 78.D-Bus-1.16.2
c79 := 79.Man-DB-2.13.1
c80 := 80.Procps-ng-4.0.7
c81 := 81.Util-linux-2.42.2
c82 := 82.E2fsprogs-1.47.4
c83 := 83.About_Debugging_Symbols
c84 := 84.Stripping
c85 := 85.Cleaning_Up

.PHONY: all

all: $(stamps)/$(c1)
all: $(stamps)/$(c2)
all: $(stamps)/$(c3)
all: $(stamps)/$(c4)
all: $(stamps)/$(c5)
all: $(stamps)/$(c6)
all: $(stamps)/$(c7)
all: $(stamps)/$(c8)
all: $(stamps)/$(c9)
all: $(stamps)/$(c10)
all: $(stamps)/$(c11)
all: $(stamps)/$(c12)
all: $(stamps)/$(c13)
all: $(stamps)/$(c14)
all: $(stamps)/$(c15)
all: $(stamps)/$(c16)
all: $(stamps)/$(c17)
all: $(stamps)/$(c18)
all: $(stamps)/$(c19)
all: $(stamps)/$(c20)
all: $(stamps)/$(c21)
all: $(stamps)/$(c22)
all: $(stamps)/$(c23)
all: $(stamps)/$(c24)
all: $(stamps)/$(c25)
all: $(stamps)/$(c26)
all: $(stamps)/$(c27)
all: $(stamps)/$(c28)
all: $(stamps)/$(c29)
all: $(stamps)/$(c30)
all: $(stamps)/$(c31)
all: $(stamps)/$(c32)
all: $(stamps)/$(c33)
all: $(stamps)/$(c34)
all: $(stamps)/$(c35)
all: $(stamps)/$(c36)
all: $(stamps)/$(c37)
all: $(stamps)/$(c38)
all: $(stamps)/$(c39)
all: $(stamps)/$(c40)
all: $(stamps)/$(c41)
all: $(stamps)/$(c42)
all: $(stamps)/$(c43)
all: $(stamps)/$(c44)
all: $(stamps)/$(c45)
all: $(stamps)/$(c46)
all: $(stamps)/$(c47)
all: $(stamps)/$(c48)
all: $(stamps)/$(c49)
all: $(stamps)/$(c50)
all: $(stamps)/$(c51)
all: $(stamps)/$(c52)
all: $(stamps)/$(c53)
all: $(stamps)/$(c54)
all: $(stamps)/$(c55)
all: $(stamps)/$(c56)
all: $(stamps)/$(c57)
all: $(stamps)/$(c58)
all: $(stamps)/$(c59)
all: $(stamps)/$(c60)
all: $(stamps)/$(c61)
all: $(stamps)/$(c62)
all: $(stamps)/$(c63)
all: $(stamps)/$(c64)
all: $(stamps)/$(c65)
all: $(stamps)/$(c66)
all: $(stamps)/$(c67)
all: $(stamps)/$(c68)
all: $(stamps)/$(c69)
all: $(stamps)/$(c70)
all: $(stamps)/$(c71)
all: $(stamps)/$(c72)
all: $(stamps)/$(c73)
all: $(stamps)/$(c74)
all: $(stamps)/$(c75)
all: $(stamps)/$(c76)
all: $(stamps)/$(c77)
all: $(stamps)/$(c78)
all: $(stamps)/$(c79)
all: $(stamps)/$(c80)
all: $(stamps)/$(c81)
all: $(stamps)/$(c82)
all: $(stamps)/$(c83)
all: $(stamps)/$(c84)
all: $(stamps)/$(c85)

$(stamps)/%:
	test -n "$(LFS)"
	mkdir -p $(dir $@)
	$(MAKE) -C $(@:$(stamps)/%=%)
	touch $@

$(stamps)/$(c1):
$(stamps)/$(c2):
$(stamps)/$(c3):
$(stamps)/$(c4):
$(stamps)/$(c5):
$(stamps)/$(c6):
$(stamps)/$(c7):
$(stamps)/$(c8):
$(stamps)/$(c9):
$(stamps)/$(c10):
$(stamps)/$(c11):
$(stamps)/$(c12):
$(stamps)/$(c13):
$(stamps)/$(c14):
$(stamps)/$(c15):
$(stamps)/$(c16):
$(stamps)/$(c17):
$(stamps)/$(c18):
$(stamps)/$(c19):
$(stamps)/$(c20):
$(stamps)/$(c21):
$(stamps)/$(c22):
$(stamps)/$(c23):
$(stamps)/$(c24):
$(stamps)/$(c25):
$(stamps)/$(c26):
$(stamps)/$(c27):
$(stamps)/$(c28):
$(stamps)/$(c29):
$(stamps)/$(c30):
$(stamps)/$(c31):
$(stamps)/$(c32):
$(stamps)/$(c33):
$(stamps)/$(c34):
$(stamps)/$(c35):
$(stamps)/$(c36):
$(stamps)/$(c37):
$(stamps)/$(c38):
$(stamps)/$(c39):
$(stamps)/$(c40):
$(stamps)/$(c41):
$(stamps)/$(c42):
$(stamps)/$(c43):
$(stamps)/$(c44):
$(stamps)/$(c45):
$(stamps)/$(c46):
$(stamps)/$(c47):
$(stamps)/$(c48):
$(stamps)/$(c49):
$(stamps)/$(c50):
$(stamps)/$(c51):
$(stamps)/$(c52):
$(stamps)/$(c53):
$(stamps)/$(c54):
$(stamps)/$(c55):
$(stamps)/$(c56):
$(stamps)/$(c57):
$(stamps)/$(c58):
$(stamps)/$(c59):
$(stamps)/$(c60):
$(stamps)/$(c61):
$(stamps)/$(c62):
$(stamps)/$(c63):
$(stamps)/$(c64):
$(stamps)/$(c65):
$(stamps)/$(c66):
$(stamps)/$(c67):
$(stamps)/$(c68):
$(stamps)/$(c69):
$(stamps)/$(c70):
$(stamps)/$(c71):
$(stamps)/$(c72):
$(stamps)/$(c73):
$(stamps)/$(c74):
$(stamps)/$(c75):
$(stamps)/$(c76):
$(stamps)/$(c77):
$(stamps)/$(c78):
$(stamps)/$(c79):
$(stamps)/$(c80):
$(stamps)/$(c81):
$(stamps)/$(c82):
$(stamps)/$(c83):
$(stamps)/$(c84):
$(stamps)/$(c85):
