#!/bin/bash

tmp="$(mktemp)"
trap 'rm $tmp' EXIT

cat << 'EOF' > $tmp
insmod part_gpt
search --no-floppy --label ESP --set=root
configfile ($root)/grub/grub.cfg
EOF

grub-mkstandalone -O x86_64-efi -o /boot/EFI/BOOT/BOOTX64.EFI "boot/grub/grub.cfg=$tmp"

mkdir -pv /boot/grub
